#CREATING ROOM WITH PLAYER_NAME
POST http://localhost:8000/room/create
content-type: application/json

{
    "title": "title teste with player",
    "player_name": "first owner"
}

###

#CREATING ROOM WITHOUT PLAYER_NAME
POST http://localhost:8000/room/create
content-type: application/json

{
    "title": "title teste without player"
}

###

#STARTING AN ROOM
POST http://localhost:8000/room/start
Content-Type: application/json

{
    "room_id":"0a26ef17-bb10-469c-b34e-de0c145e279d",
    "player_id":"308b3a51-0acc-4542-b362-362f7a4faf57"
}
###

#FINISH AN ROOM
POST http://localhost:8000/room/finish
Content-Type: application/json

{
    "room_id":"0a26ef17-bb10-469c-b34e-de0c145e279d",
    "player_id":"308b3a51-0acc-4542-b362-362f7a4faf57"
}