#CREATING ROOM WITH PLAYER_NAME
POST http://localhost:8000/room/create
content-type: application/json

{
    "title": "title teste with player",
    "player_name": "first owner"
}

###

#CREATING ROOM WITHOUT PLAYER_NAME
POST http://localhost:8000/room/create
content-type: application/json

{
    "title": "title teste without player"
}

###

#STARTING AN ROOM
POST http://localhost:8000/room/start
Content-Type: application/json

{
    "room_id":"06c895b4-4a97-4fe2-a3f9-583299f84e4c",
    "player_id":"bafe5c50-6d23-4a60-b2f9-9465109fc5d1"
}
###

#FINISH AN ROOM
POST http://localhost:8000/room/finish
Content-Type: application/json

{
    "room_id":"06c895b4-4a97-4fe2-a3f9-583299f84e4c",
    "player_id":"bafe5c50-6d23-4a60-b2f9-9465109fc5d1"
}
###

#JOIN ON A ROOM
POST http://localhost:8000/player/join
Content-Type: application/json

{
    "room_number": 22
}
###

#JOIN ON A ROOM WHITH PLAYER NAME
POST http://localhost:8000/player/join
Content-Type: application/json

{
    "room_number": 22,
    "player_name": "player teste" 
}
###

#EXIT ON A ROOM WHITH PLAYER NAME
POST http://localhost:8000/player/join
Content-Type: application/json

{
    "player_id": "db85441c-5451-497c-9552-9f4ca552a821"
}